# Generated by Django 2.2.10 on 2020-03-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
